### ISSUE TITLE
feat: Stack Trace

### ISSUE THREAD

**Issue by refcell** [huff-language/huff-rs#132]
## Overview

> **Warning**
> This is likely a very big task that will touch a lot of internal huff compiler workings + require vigorous testing.

This would look something like [the huff style guide](https://www.notion.so/Huff-Std-Style-Guideline-9c2ceaa795934c38be0b2f2d10042fe9):

```
0x20    // [value]
0x00    // [offset, value]
mstore  // []
```

Where the stack is represented in comments that are right column-aligned.

We should likely be performed at the [huff_codegen](./huff_codegen) stage where we generate bytecode from an AST. That is, when parsing the `Statement`s in a `MacroDefinition`'s body, each `Statement` could have a respective stack trace/comment.

**Comment by iFrostizz** [comment]
Hey @abigger87 , been working on that recently and it's almost ready!
The only thing that is missing for now is the check for variable names and their value in the stack, but that won't be much work from there.
See: https://github.com/huff-language/huff-rs/compare/main...iFrostizz:huff-rs:feat/assert
