### ISSUE TITLE
HIP-01: Syntactic sugar for function signatures 

### ISSUE THREAD

**Issue by clemlak** [huff-language/huff-rs#149]
## Simple Summary

Computing function signatures is a bit of a hassle and having them displayed as hardcoded values increases the technical debt.
Some *syntactic sugar* could be added to the language itself (e.g. `FUNC_SIG('set(uint256)')`) that will allow developers to compute function signatures directly within the source code.

## Motivation

Function signatures are currently hardcoded in Huff contracts, which means that `set(uint256)` will be displayed as `0x60fe47b1`. This current solution is not very practical, since developers may have to use an external tool to compute the full keccak-256 hash, trim the extra bytes manually to get the function signature itself, copy / paste it into the source code and eventually add a comment to remember where this value is coming from.

Here is a snippet of the current situation:

```cs
#define macro MAIN() = takes(0) returns (0) {
  0x00 calldataload
  0xe0 shr
  dup1
  0x60fe47b1 // signature of `set(uint256)`
  eq
  set jumpi
  dup1
  0x6d4ce63c // signature of `get()`
  eq
  get jumpi
  set:
    SET()
  get:
    GET()
}
```

## Specification

Via the new `FUNC_SIG` keyword, developers would be able to compute function signatures directly in their Huff contracts.
Here is a proposed implementation:

```cs
#define macro MAIN() = takes(0) returns (0) {
  0x00 calldataload
  0xe0 shr
  dup1
  FUNC_SIG('set(uint256)')
  eq
  set jumpi
  dup1
  FUNC_SIG('get()')
  eq
  get jumpi
  set:
    SET()
  get:
    GET()
}
```

The compiler will interpret the *helper function* `FUNC_SIG` and replace it with the correct function signature. For example:
- `FUNC_SIG('set(uint256)')` will become `0x60fe47b1`
- `FUNC_SIG('get()')` will become `0x6d4ce63c`

## Notes

A similar *helper function* could be added to get the hash of events: `EVENT_HASH('...')`.

**Comment by clabby** [comment]
Implemented in #148 :smile:
