### ISSUE TITLE
feat: constructor bootstrap code overrides

### ISSUE THREAD

**Issue by ncitron** [huff-language/huff-rs#195]
I think it could be useful if we allowed the user to override the normal bootstrap code with something custom. This could be used in multiple niche cases, such as metamorphic contracts. Additionally, since Huff is often used for education purposes, some may want to write the bootstrap code themselves to better understand the contract deployment process.

I see two main ways of accomplishing this:
1. If a constructor contains the `RETURN` opcode in it, automatically omit the bootstrap code.
2. Add a command line flag to omit the bootstrap code.

I'd be happy to implement either of these myself, but want to make sure that the change would be well received first.

**Comment by clabby** [comment]
Definitely think this could be a cool feature, and I'm sure some people could find it useful. I'm for you working on it if you'd like, wdyt @abigger87?

**Comment by abigger87** [comment]
This sounds like an awesome feature, let's do it!

**Comment by abigger87** [comment]
Completed in #197
