### ISSUE TITLE
bug: __FUNC_SIG computes wrong selector of custom errors

### ISSUE THREAD

**Issue by Philogy** [huff-language/huff-rs#212]
**Version:** Result of `huffc -V` => `huffc 0.3.0`

## Description
The huff compiler computes the wrong selector for custom errors when using `__FUNC_SIG`.

## Steps to Recreate
1. Define custom error in huff contract `#define error NotOwner()`
2. Add `__FUNC_SIG(NotOwner)` to macro
3. Compile using `huffc MyContract.huff -b`

**Expected Result:** `__FUNC_SIG(NotOwner)` gets compiled to `6330cd7471` (`PUSH4 0x30cd7471`)
**Actual Result:** `__FUNC_SIG(NotOwner)`  gets compiled to `632a4cb61e` (`PUSH4 0x2a4cb61e`)

## Other Details
Upon some investigation it looks like `__FUNC_SIG` only hashes the name of errors instead of hashing the entire name according to the [ABI spec](https://docs.soliditylang.org/en/v0.8.15/abi-spec.html#errors): `bytes4(keccak256("NotOwner")) => 0x2a4cb61e`

**Comment by clabby** [comment]
Fixed in #224
