### ISSUE TITLE
[Bug?] Leading 0x00 of PUSH opcode argument value is deleted

### ISSUE THREAD

**Issue by minaminao** [huff-language/huff-rs#226]
```
#define macro MAIN() = takes (0) returns (0) {
    0x1111 // PUSH2 0x1111  [0x1111]
    0x0011 // PUSH1 0x11    [0x11, 0x1111]   <- I expected PUSH2 0x0011
    pc     // PC            [0x5]            <- I expected [0x6]
}
```

It causes unexpected bugs using PC :)

**Comment by refcell** [comment]
As requested in #244, we now support what are called "push overrides". This allows you to explicitly prefix hex literals with `PUSH` opcodes as of our merge into #220. Hopefully this answers your question :)

**Comment by minaminao** [comment]
Push override is great! Thank you
