### ISSUE TITLE
__codesize(CONSTRUCTOR) & __codesize(MAIN) return incorrect size

### ISSUE THREAD

**Issue by obatirou** [huff-language/huff-rs#238]
1. It seems `__codesize(CONSTRUCTOR)`called from within the constructor itself will return an incorrect size.
Real case commit example [here](https://github.com/oguimbal/HyVM/blob/4e760d4535cf0e55d4453583c9b1484e5f3d3f9c/src/HyVM.huff#L24).
To add an immutable in the constructor, this code appends at the end of the runtimeCode the wanted immutable and return the bytecode. But in this case, the size returned by `__codesize(CONSTRUCTOR)` is off by `0x2` and was fixed manually.

2. Used an other way of calculating the runtimeCode size with `__codesize(MAIN)` (there is no functions only macros in the code so `__codesize(MAIN)==runtimeCode` if I am not mistaken) but this time the size was off by `0x200` which should be the size of the jump table. Hence it leads me to believe the jump table is not taken into account in `__codesize(MAIN)`.
Branch with real case commit example [here](https://github.com/oguimbal/HyVM/compare/main...check-delegatecall-investigation).

Began exchange with @cheethas on discord whom had a first look into it and might be able to give some further info on this.
Let me know if anything is unclear, need any further information or if I missed anything !

**Comment by cheethas** [comment]
Thanks for posting this, your feedback in identifying these issues has been invaluable. 

After a discussion with @clabby we've identified a path to fixing issue number 1 above. PR #240 is a work in progress implementation that resolves the issue in the contract you have linked. You should no longer need to add 0x2 if compiling with the version in the pr. That being said, there are a number of tests and scenarios I would like to explore before merging the work into nightly.

Regarding 2. Code tables etc are appended to the end of the `MAIN` bytecode but are not considered part of the `MAIN` macro themselves. The usecase in your code seems like it will be common enough to warrant another builtin that can get the codesize of the entire runtime bytecode.

**Comment by obatirou** [comment]
Thanks a lot for looking into it !
I can confirm indeed that if compiling with PR version, there is no need for the fix `0x02` 👍
Did not know about code tables not being part of the `MAIN` bytecode. The second example make more sense now !
Will follow this and update once everything is merged.

**Comment by cheethas** [comment]
Stoked its working for you, ill update you when I get the work complete.

**Comment by cheethas** [comment]
I think the work is complete, ive tidied it up alot, waiting on a review then should be gtg. I'll get working on the builtin

**Comment by refcell** [comment]
Completed in #240 by @cheethas
