### ISSUE TITLE
feat: Support function overloading for __FUNC_SIG usage

### ISSUE THREAD

**Issue by goncaloMagalhaes** [huff-language/huff-rs#242]
Would be nice having some way to select a given function definition when using `__FUNC_SIG(myDopeFunction)` in the cases where ew have function overloading.

**Comment by iFrostizz** [comment]
would writing the full signature "myDopeFunction(address)" be a good solution here ? e.g: `__FUNC_SIG(myDopeFunction(address))`
This could also be by default, even when there is no overloading situation and would not require to write a `#define function` keyword

**Comment by jtriley-eth** [comment]
This is already possible by using strings instead:
```rust
__FUNC_SIG("a(uint256)")
__FUNC_SIG("a()")
```
@goncaloMagalhaes how would you go about overloading without strings?

**Comment by goncaloMagalhaes** [comment]
Yeah I opened this issue as suggested on Huff's discord, the usage of strings is just not as clean as the typical usage of the function name when there's no need for overload, but indeed I don't see any viable path forward. Besides, since it's still possible to overload using strings, I guess we can just close this.
