### ISSUE TITLE
Allow users to use `PUSH` opcode without breaking the compiler

### ISSUE THREAD

**Issue by misirov** [huff-language/huff-rs#244]
Although simplicity is great, there are valid reasons for users to use the `PUSH` opcode.
```
Error: Unmatched Jump Label
-> ./huff-project-template/src/Test.huff:268-273
       |
  > 10 |     PUSH1 0x20            // [ 20 ] <- stack
       |
```
If `PUSH` is used in the right context, the compiler should be able to ignore it.
```diff
#define macro MAIN() = takes(0) returns(0) {
+ PUSH1 0x20
+ PUSH1 0x01
add
```

**Comment by cheethas** [comment]
added in https://github.com/huff-language/huff-rs/pull/218
