### ISSUE TITLE
Huffc 0.3.1 logs ident_str from jump/code table throwing foundry errors

### ISSUE THREAD

**Issue by obatirou** [huff-language/huff-rs#262]
Pinned the version `0.3.1` (`nightly-94c34e402a46365fee29863aa08558af178c2b94`) in CI and local but `Huffc` logs some `ident_str`, it seems to be related to jumptable
`huffc ./src/HyVM.huff` ([link to huff parser line concerned](https://github.com/huff-language/huff-rs/blob/main/huff_parser/src/lib.rs#LL1113))
![image](https://user-images.githubusercontent.com/92337658/228468813-8d771fee-7141-41ef-b2e6-9880f16f3eaa.png)

This cause errors in foundry when running tests but tests still pass
![image](https://user-images.githubusercontent.com/92337658/228468949-6e096fb4-67ea-4f05-ab55-9a812607de02.png)

When downgrading to` nightly-d4638680736ad104290bc7a28542c058a18debf4`, those logs are not present anymore

Link to [diff of the 2 huff-rs versions here](https://github.com/huff-language/huff-rs/compare/nightly-d4638680736ad104290bc7a28542c058a18debf4...0.3.1)

I suppose those logs are not processed by `ffi` and the flow continue like it should as all tests still pass

It happens also in Huffmate repo when dealing with jumpable or code table 
`JumpTableUtilWrappers` jumptables [here](https://github.com/huff-language/huffmate/blob/main/test/utils/mocks/JumpTableUtilWrappers.huff#L7)
![Capture d’écran 2023-03-29 à 10 18 07](https://user-images.githubusercontent.com/92337658/228471419-6d74dc52-09ec-4e43-b8f3-2af413e23093.png)

`Trigonometry` code table [here](https://github.com/huff-language/huffmate/blob/main/src/math/Trigonometry.huff#L39)
![Capture d’écran 2023-03-29 à 10 17 46](https://user-images.githubusercontent.com/92337658/228471429-41fae0a1-017d-464c-801c-5944e75669f9.png)

[Link](https://discord.com/channels/980519274600882306/980636187779805224/1089888719391166475) to discord discussion

**Comment by Maddiaa0** [comment]
Fixed in 0.3.2

**Comment by obatirou** [comment]
Hey @Maddiaa0 
I am not sure it is solved 
`huffc ./src/HyVM.huff --bytecode -e paris` still outputs this: 
<img width="411" alt="Capture d’écran 2023-07-11 à 10 25 41" src="https://github.com/huff-language/huff-rs/assets/92337658/e5845f23-0603-4216-93e7-d82b4c0a5249">
And in tests: 
<img width="1368" alt="Capture d’écran 2023-07-11 à 10 24 06" src="https://github.com/huff-language/huff-rs/assets/92337658/adf463e9-1a09-4c1f-91cf-02e5cc5f9796">

**Comment by Maddiaa0** [comment]
Ah the fix is only in master but nightly has released from stage without the fix, merging to stage and re-releaseing
