### ISSUE TITLE
Shanghai support

### ISSUE THREAD

**Issue by MathisGD** [huff-language/huff-rs#271]
The Shanghai Execution Layer upgrade is around the corner. I have listed what I think that should be changed in `huff-rs`: 

- [x] Add support for `PUSH0` ([EIP-3855](https://eips.ethereum.org/EIPS/eip-3855)) (#272)
- [ ] Warn `SELFDESTRUCT` users as recommended in the upgrade spec ([EIP-6049](https://eips.ethereum.org/EIPS/eip-6049)) (#275)

Am I missing something ?

### Ressources

- [Shanghai Network Upgrade Specification](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md)

**Comment by Sabnock01** [comment]
Would [EIP-3860](https://eips.ethereum.org/EIPS/eip-3860) not also be needed? Not sure how creation code works with the - [ ] compiler.

**Comment by MathisGD** [comment]
> Would [EIP-3860](https://eips.ethereum.org/EIPS/eip-3860) not also be needed? Not sure how creation code works with the compiler.

I don't think that it has to be done, as the compiler already doesn't check that the runtime code doesn't exceed the limit size IIUC.
