### ISSUE TITLE
feat(huff_cli): Input constructor args interactively

### ISSUE THREAD

**Issue by clabby** [huff-language/huff-rs#88]
# Overview

At the moment, constructor args are passed via the `inputs` flag in the CLI, e.g. `huff ERC20.huff --inputs "TST" 1000 0x42069...` 

It would be nice if devs could omit some or all of the constructor args in favor of the compiler generating the contract's ABI, detecting which constructor arguments are missing, and prompting the user to input them. (idea: @abigger87)

The interactive input functionality should abi encode the inputs for the user and detect type mismatches

**Comment by abigger87** [comment]
Completed in #146
